name: dbscan_dart
description: A lightweight, pure-Dart implementation of the DBSCAN clustering algorithm with KD-Tree optimization.
version: 1.1.1
repository: https://github.com/helpisdev/dbscan_dart
homepage: https://github.com/helpisdev/dbscan_dart
documentation: https://github.com/helpisdev/dbscan_dart/blob/main/README.md
issue_tracker: https://github.com/helpisdev/dbscan_dart/issues

topics:
  - clustering
  - algorithm
  - machine-learning
  - spatial
  - data-analysis

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.16.0

dev_dependencies:
  benchmark_harness: ^2.3.1
  lints: ^6.0.0
  melos: ^6.3.3
  test: ^1.24.0
